---
--- 

- name: Install fastbook tutorial environment
  hosts: localhost
  user: ubuntu
  tasks:

    - name: install miniconda
      shell: 
        cmd: ./install_miniconda.sh
        chdir: /home/ubuntu
        creates: /home/ubuntu/miniconda3
