---
- name: Install fastbook tutorial environment
  hosts: localhost
  user: ubuntu
  tasks:
    - name: install miniconda
      shell:
        cmd: sh ./install_miniconda.sh > conda_install.log
        creates: /home/ubuntu/miniconda3
